import { StyleSheet } from 'react-native';
import { theme, type AppTheme } from '@/theme';

/**
 * Cart styles live here rather than in `CartScreen` so the section components
 * under `./components` can share one stylesheet without importing the screen
 * back (which would be a cycle).
 */
export const createStyles = (theme: AppTheme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    screen: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    content: {
      paddingHorizontal: theme.spacing.screen,
      paddingTop: 8,
      paddingBottom: 128,
      gap: 10,
    },
    cartHeader: {
      gap: 8,
      paddingHorizontal: 2,
    },
    cartHeaderTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    cartHeaderCopy: {
      flex: 1,
      gap: 2,
    },
    cartHeaderTitle: {
      color: theme.colors.text,
      fontSize: 25,
      lineHeight: 29,
      fontWeight: '800',
      letterSpacing: -0.9,
    },
    cartHeaderSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 12,
      fontWeight: '600',
    },
    cartHeaderMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    cartHeaderChip: {
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: theme.colors.primarySoft,
    },
    cartHeaderChipText: {
      color: theme.colors.primary,
      fontSize: 10,
      fontWeight: '800',
    },
    cartHeaderMetaText: {
      color: theme.colors.secondaryText,
      fontSize: 11,
      fontWeight: '600',
    },
    offerPaletteSection: {
      borderRadius: 24,
      paddingVertical: 12,
      gap: 10,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 18,
      elevation: 3,
    },
    offerPaletteHeader: {
      paddingHorizontal: 14,
      gap: 4,
    },
    offerPaletteHeaderTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    offerPaletteHeaderTitle: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 15.5,
      lineHeight: 19,
      fontWeight: '800',
    },
    offerPaletteHeaderSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 10.5,
      lineHeight: 13.5,
    },
    offerPaletteHeaderCount: {
      minWidth: 24,
      height: 24,
      borderRadius: 12,
      textAlign: 'center',
      textAlignVertical: 'center',
      overflow: 'hidden',
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF3EA',
      color: theme.colors.primary,
      fontSize: 10.5,
      fontWeight: '800',
      paddingTop: 5,
      flexShrink: 0,
    },
    offerPaletteList: {
      paddingHorizontal: 14,
      paddingRight: 28,
    },
    offerPaletteSpacer: {
      width: 10,
    },
    offerPaletteCard: {
      borderRadius: 16,
      paddingHorizontal: 11,
      paddingVertical: 10,
      borderWidth: 1,
      gap: 8,
      minHeight: 140,
      justifyContent: 'space-between',
    },
    offerPaletteIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    offerPaletteRowTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
    },
    offerPaletteCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    offerPaletteTitleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 6,
    },
    offerPaletteDiscountLabel: {
      flex: 1,
      fontSize: 12.5,
      lineHeight: 15.5,
      fontWeight: '800',
    },
    offerPaletteOfferTitle: {
      color: theme.colors.text,
      fontSize: 11.5,
      lineHeight: 14.5,
      fontWeight: '700',
      minHeight: 29,
    },
    offerPaletteStatusBadge: {
      borderRadius: 999,
      paddingHorizontal: 7,
      paddingVertical: 3,
      flexShrink: 0,
    },
    offerPaletteStatusText: {
      fontSize: 9,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    offerPaletteMeta: {
      color: theme.colors.hint,
      fontSize: 10,
      fontWeight: '600',
    },
    offerPaletteMessage: {
      color: theme.colors.secondaryText,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '600',
      minHeight: 28,
    },
    offerPaletteFooter: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: 10,
    },
    offerPaletteMetaBlock: {
      flex: 1,
      gap: 3,
      minWidth: 0,
    },
    offerPaletteRestaurant: {
      color: theme.colors.hint,
      fontSize: 10,
      fontWeight: '700',
    },
    offerPaletteActionButton: {
      minHeight: 30,
      borderRadius: 999,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    offerPaletteActionButtonText: {
      fontSize: 11,
      fontWeight: '800',
    },
    offerPaletteLockedPill: {
      minHeight: 30,
      borderRadius: 999,
      paddingHorizontal: 11,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF4EC',
    },
    offerPaletteLockedText: {
      color: theme.colors.hint,
      fontSize: 10.5,
      fontWeight: '800',
    },
    clearChip: {
      borderRadius: 999,
      paddingHorizontal: 11,
      paddingVertical: 7,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF5EE',
      borderWidth: 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
    },
    clearChipText: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: '800',
    },
    fulfillmentCard: {
      borderRadius: 22,
      padding: 12,
      gap: 9,
      backgroundColor:
        theme.mode === 'dark'
          ? theme.colors.surface
          : theme.colors.surfaceRaised,
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOpacity: theme.mode === 'dark' ? 0.14 : 0.04,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: theme.mode === 'dark' ? 18 : 16,
      elevation: theme.mode === 'dark' ? 4 : 2,
    },
    fulfillmentHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    fulfillmentHeaderCopy: {
      flex: 1,
      gap: 2,
    },
    fulfillmentPrimaryAction: {
      flexDirection: 'row',
      gap: 4,
      minHeight: 32,
      paddingHorizontal: 11,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceRaised : '#FFF5EE',
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
    },
    fulfillmentPrimaryActionText: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: '800',
    },
    fulfillmentSummaryPill: {
      alignSelf: 'flex-start',
      paddingHorizontal: 11,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor:
        theme.mode === 'dark'
          ? theme.colors.surfaceRaised
          : theme.colors.primarySoft,
    },
    fulfillmentSummaryPillText: {
      color:
        theme.mode === 'dark' ? theme.colors.primary : theme.colors.primary,
      fontSize: 10,
      fontWeight: '800',
    },
    fulfillmentTitle: {
      color: theme.colors.text,
      fontSize: 14.5,
      fontWeight: '800',
    },
    fulfillmentSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 10.5,
      lineHeight: 15,
    },
    fulfillmentToggle: {
      flexDirection: 'row',
      gap: 6,
      padding: 3,
      borderRadius: 18,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.background : '#FFF7F1',
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.06)',
    },
    fulfillmentToggleButton: {
      flex: 1,
      minHeight: 36,
      paddingHorizontal: 12,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 7,
      backgroundColor:
        theme.mode === 'dark' ? 'transparent' : theme.colors.surfaceRaised,
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor: theme.colors.border,
    },
    fulfillmentToggleButtonActive: {
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceRaised : theme.colors.text,
      borderColor:
        theme.mode === 'dark' ? theme.colors.chipBorder : theme.colors.text,
      shadowColor: theme.colors.shadow,
      shadowOpacity: theme.mode === 'dark' ? 0.12 : 0,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 12,
      elevation: theme.mode === 'dark' ? 2 : 0,
    },
    fulfillmentToggleButtonDisabled: {
      backgroundColor: theme.mode === 'dark' ? 'transparent' : '#FFFDFC',
      borderColor: theme.mode === 'dark' ? 'transparent' : theme.colors.border,
    },
    fulfillmentToggleText: {
      color:
        theme.mode === 'dark' ? theme.colors.hint : theme.colors.secondaryText,
      fontSize: 12,
      fontWeight: '800',
    },
    fulfillmentToggleTextActive: {
      color: theme.mode === 'dark' ? theme.colors.text : theme.colors.white,
    },
    fulfillmentToggleTextDisabled: {
      color: theme.colors.hint,
    },
    fulfillmentSelectedCard: {
      gap: 9,
      borderRadius: 18,
      padding: 10,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFFCF9',
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor: theme.colors.border,
    },
    fulfillmentSelectedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
    },
    fulfillmentSelectedIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceRaised : '#FFF1E7',
    },
    fulfillmentSelectedCopy: {
      flex: 1,
      gap: 2,
    },
    fulfillmentSelectedEyebrow: {
      color: theme.colors.hint,
      fontSize: 9.5,
      fontWeight: '800',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    fulfillmentSelectedTitle: {
      color: theme.colors.text,
      fontSize: 14.5,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
    fulfillmentSelectedSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 10,
      lineHeight: 15,
      fontWeight: '600',
    },
    fulfillmentWarning: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 7,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.dangerSoft : '#FFF5EF',
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor: theme.mode === 'dark' ? theme.colors.border : '#FFD8C3',
    },
    fulfillmentWarningText: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
    },
    fulfillmentBody: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      borderRadius: 16,
      padding: 10,
      backgroundColor:
        theme.mode === 'dark'
          ? theme.colors.surfaceRaised
          : theme.colors.surfaceRaised,
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor: theme.colors.border,
    },
    fulfillmentBodyWarning: {
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.dangerSoft : '#FFF3EC',
      borderWidth: 1,
      borderColor: theme.mode === 'dark' ? theme.colors.primary : '#FFB892',
    },
    fulfillmentInfo: {
      flex: 1,
      gap: 4,
    },
    fulfillmentLabel: {
      color: theme.colors.hint,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    fulfillmentValue: {
      color: theme.colors.text,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700',
    },
    fulfillmentValueWarning: {
      color: theme.colors.text,
    },
    fulfillmentWarningBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginBottom: 4,
    },
    fulfillmentWarningTextCard: {
      flex: 1,
      color: theme.colors.primary,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '700',
    },
    fulfillmentAction: {
      flexDirection: 'row',
      gap: 4,
      minHeight: 34,
      paddingHorizontal: 11,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.mode === 'dark' ? theme.colors.surface : '#FFF5EE',
      borderWidth: theme.mode === 'dark' ? 0 : 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
    },
    fulfillmentActionHighlighted: {
      backgroundColor: theme.colors.primary,
      borderWidth: 0,
    },
    fulfillmentActionText: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: '800',
    },
    fulfillmentActionTextHighlighted: {
      color: theme.colors.white,
    },
    fulfillmentMetaPill: {
      minHeight: 34,
      paddingHorizontal: 11,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surface : theme.colors.primarySoft,
    },
    fulfillmentMetaText: {
      color:
        theme.mode === 'dark' ? theme.colors.primary : theme.colors.primary,
      fontSize: 10,
      fontWeight: '800',
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    sectionHeaderCopy: {
      flex: 1,
      gap: 2,
    },
    sectionTitle: {
      color: theme.colors.text,
      fontSize: 17,
      fontWeight: '800',
    },
    sectionSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 11,
    },
    sectionCount: {
      minWidth: 26,
      height: 26,
      borderRadius: 13,
      textAlign: 'center',
      textAlignVertical: 'center',
      overflow: 'hidden',
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF3EA',
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: '800',
      paddingTop: 5,
    },
    itemsPanel: {
      borderRadius: 24,
      padding: 14,
      gap: 12,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 18,
      elevation: 3,
    },
    itemsColumn: {
      gap: 10,
    },
    addMoreItemsRow: {
      marginTop: 2,
      minHeight: 48,
      borderRadius: 18,
      paddingHorizontal: 14,
      paddingVertical: 11,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF7F1',
      borderWidth: 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
    },
    addMoreItemsCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    addMoreItemsTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    addMoreItemsTitle: {
      color: theme.colors.primary,
      fontSize: 13.5,
      fontWeight: '800',
    },
    addMoreItemsSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 11.5,
      fontWeight: '600',
    },
    itemCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: 18,
      padding: 10,
      backgroundColor: theme.mode === 'dark' ? theme.colors.surface : '#FFFCFA',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    itemImageWrap: {
      position: 'relative',
    },
    itemImage: {
      width: 58,
      height: 58,
      borderRadius: 15,
      backgroundColor: theme.colors.card,
    },
    foodBadge: {
      position: 'absolute',
      left: 6,
      top: 6,
      width: 16,
      height: 16,
      borderRadius: 5,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1.5,
    },
    foodBadgeVeg: {
      borderColor: theme.colors.offer,
    },
    foodBadgeNonVeg: {
      borderColor: theme.colors.deepRed,
    },
    itemBody: {
      flex: 1,
      gap: 4,
    },
    itemTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    itemTitle: {
      flex: 1,
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    foodDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    foodDotVeg: {
      backgroundColor: theme.colors.offer,
    },
    foodDotNonVeg: {
      backgroundColor: theme.colors.deepRed,
    },
    itemMeta: {
      color: theme.colors.secondaryText,
      fontSize: 11,
    },
    itemCustomizationMeta: {
      color: theme.colors.hint,
      fontSize: 11,
      lineHeight: 16,
    },
    itemFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginTop: 2,
    },
    itemPriceStack: {
      gap: 1,
    },
    itemPriceLabel: {
      color: theme.colors.hint,
      fontSize: 9,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    itemPrice: {
      color: theme.colors.secondaryText,
      fontSize: 11,
      fontWeight: '700',
    },
    itemTotal: {
      color: theme.colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    quantityBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderRadius: 999,
      paddingHorizontal: 7,
      paddingVertical: 5,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF3EA',
      borderWidth: 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
    },
    quantityButton: {
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: theme.colors.surfaceRaised,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.04,
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 6,
      elevation: 1,
    },
    quantityAction: {
      color: theme.colors.primary,
      fontSize: 15,
      fontWeight: '800',
    },
    quantityCount: {
      minWidth: 14,
      textAlign: 'center',
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: '800',
    },
    upsellSection: {
      gap: 8,
    },
    upsellSectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: 12,
    },
    upsellSectionTitle: {
      color: theme.colors.text,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
    upsellSectionMeta: {
      color: theme.colors.secondaryText,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    upsellCarouselContent: {
      paddingRight: 6,
    },
    upsellCarouselSpacer: {
      width: 10,
    },
    upsellCarouselCard: {
      minHeight: 142,
      borderRadius: 18,
      padding: 12,
      gap: 6,
      overflow: 'hidden',
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.10)',
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.06,
      shadowOffset: { width: 0, height: 6 },
      shadowRadius: 14,
      elevation: 3,
    },
    upsellCarouselGlow: {
      position: 'absolute',
      right: -18,
      top: -10,
      width: 94,
      height: 94,
      borderRadius: 999,
      backgroundColor: 'rgba(255,82,0,0.08)',
    },
    upsellCarouselHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    upsellBadge: {
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.primarySoft : '#FFF1E7',
    },
    upsellBadgeText: {
      color: theme.colors.primary,
      fontSize: 9,
      fontWeight: '800',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    upsellPrice: {
      color: theme.colors.primary,
      fontSize: 14,
      fontWeight: '800',
    },
    upsellCarouselTitle: {
      color: theme.colors.text,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '800',
      letterSpacing: -0.4,
      paddingRight: 14,
    },
    upsellCarouselText: {
      color: theme.colors.secondaryText,
      fontSize: 10,
      lineHeight: 14,
      paddingRight: 14,
    },
    upsellFooter: {
      marginTop: 'auto',
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: 10,
    },
    upsellFooterCopy: {
      flex: 1,
      gap: 2,
    },
    upsellFooterLabel: {
      color: theme.colors.hint,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    upsellFooterItems: {
      color: theme.colors.text,
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '700',
    },
    upsellCarouselButton: {
      minHeight: 32,
      borderRadius: 12,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
    },
    upsellCarouselButtonSuccessRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    upsellCarouselButtonText: {
      color: theme.colors.white,
      fontSize: 11,
      fontWeight: '800',
    },
    formCard: {
      borderRadius: 22,
      padding: 14,
      gap: 8,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.04,
      shadowOffset: { width: 0, height: 8 },
      shadowRadius: 16,
      elevation: 2,
    },
    formAccordionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    formAccordionCopy: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    formAccordionBody: {
      paddingTop: 4,
    },
    formTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    formSubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 11,
      lineHeight: 16,
    },
    input: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.border,
      backgroundColor: theme.mode === 'dark' ? theme.colors.surface : '#FFFDFC',
      paddingHorizontal: 16,
      paddingVertical: 11,
      textAlignVertical: 'top',
      color: theme.colors.text,
      fontSize: 14,
    },
    notesInput: {
      minHeight: 78,
    },
    summaryCard: {
      borderRadius: 24,
      padding: 15,
      gap: 10,
      backgroundColor:
        theme.mode === 'dark' ? theme.colors.surfaceAlt : '#FFF8F3',
      borderWidth: 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.05,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 18,
      elevation: 3,
    },
    summaryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    summaryTitle: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    summarySubtitle: {
      color: theme.colors.secondaryText,
      fontSize: 11,
      marginTop: 3,
    },
    summaryBadge: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: '800',
    },
    summaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingVertical: 2,
    },
    summaryLabel: {
      color: theme.colors.secondaryText,
      fontSize: 13,
    },
    summaryValue: {
      color: theme.colors.text,
      fontSize: 13,
      fontWeight: '700',
    },
    summaryDiscountLabel: {
      color: theme.colors.success,
    },
    summaryDiscountValue: {
      color: theme.colors.success,
    },
    summaryDivider: {
      height: 1,
      backgroundColor: theme.colors.divider,
    },
    totalLabel: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    totalValue: {
      color: theme.colors.text,
      fontSize: 18,
      fontWeight: '800',
    },
    checkoutBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: theme.spacing.screen,
      paddingTop: 12,
      backgroundColor:
        theme.mode === 'dark'
          ? theme.colors.modalSurface
          : 'rgba(255,255,255,0.98)',
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.1,
      shadowOffset: { width: 0, height: -8 },
      shadowRadius: 18,
      elevation: 16,
    },
    checkoutSummary: {
      flex: 1,
      paddingLeft: 4,
      gap: 3,
    },
    checkoutCaption: {
      color: theme.colors.hint,
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    checkoutAmount: {
      color: theme.colors.text,
      fontSize: 24,
      lineHeight: 28,
      fontWeight: '800',
      letterSpacing: -0.8,
    },
    checkoutMeta: {
      color: theme.colors.secondaryText,
      fontSize: 10,
      lineHeight: 14,
      fontWeight: '700',
    },
    checkoutButton: {
      minHeight: 52,
      minWidth: 168,
      paddingHorizontal: 20,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
      shadowColor: 'rgba(255,82,0,0.28)',
      shadowOpacity: 0.24,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 16,
      elevation: 8,
    },
    checkoutButtonDisabled: {
      opacity: 0.55,
    },
    checkoutButtonText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyWrap: {
      flex: 1,
      padding: theme.spacing.screen,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyCard: {
      width: '100%',
      borderRadius: 28,
      padding: 22,
      gap: 12,
      backgroundColor: theme.colors.surfaceRaised,
      borderWidth: 1,
      borderColor:
        theme.mode === 'dark' ? theme.colors.border : 'rgba(255,82,0,0.08)',
    },
    emptyEyebrow: {
      color: theme.colors.primary,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    emptyTitle: {
      color: theme.colors.text,
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '800',
      letterSpacing: -0.8,
    },
    emptyText: {
      color: theme.colors.secondaryText,
      fontSize: 14,
      lineHeight: 22,
    },
    emptyButton: {
      marginTop: 8,
      minHeight: 50,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
    },
    emptyButtonText: {
      color: theme.colors.white,
      fontSize: 15,
      fontWeight: '800',
    },
  });

export const styles = createStyles(theme);
