import { StyleSheet } from 'react-native';
import { radius, space, type, type AppTheme } from '@/theme';

export const createStyles = ({ colors }: AppTheme) =>
  StyleSheet.create({
    scroll: { padding: space.lg, paddingBottom: 40 },
    // A settings list is read, not scanned across; it stays narrow on a tablet.
    column: { width: '100%', maxWidth: 640, alignSelf: 'center', gap: space.xxl },
    profile: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.lg,
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: radius.xl,
      padding: space.xl,
    },
    avatar: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.accent,
    },
    avatarText: { fontSize: 24, fontWeight: '900', color: colors.onAccent },
    profileText: { flex: 1, gap: 4, minWidth: 0 },
    profileName: { ...type.title, color: colors.text },
    profileEmail: { ...type.caption, color: colors.textMuted },
    section: { gap: space.sm },
    sectionTitle: { ...type.overline, color: colors.textMuted, paddingHorizontal: space.xs },
    group: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderWidth: 1,
      borderRadius: radius.xl,
      overflow: 'hidden',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: space.lg,
      paddingVertical: space.md,
      minHeight: 64,
    },
    rowDivider: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
    rowSelected: { backgroundColor: colors.accentSoft },
    rowText: { flex: 1, gap: 2, minWidth: 0 },
    rowTitle: { ...type.bodyStrong, color: colors.text },
    rowBody: { ...type.caption, color: colors.textMuted },
    footnote: { ...type.caption, color: colors.textMuted, paddingHorizontal: space.xs },
    radio: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: colors.accent },
    signOut: {
      minHeight: 56,
      borderRadius: radius.lg,
      borderWidth: 1.5,
      borderColor: colors.danger,
      backgroundColor: colors.dangerSoft,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    signOutText: { fontSize: 17, fontWeight: '800', color: colors.danger },
    testButton: {
      minHeight: 44,
      borderRadius: radius.md,
      paddingHorizontal: space.lg,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    testButtonText: { fontSize: 15, fontWeight: '800', color: colors.text },
    pillCell: { justifyContent: 'center' },
    pressed: { opacity: 0.7 },
  });
